export const Fishlistapi =[
    {
      "price": "165.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_FWPOMFRET",
      "thumb": "https://assets.tendercuts.in/product/S/F/cab653d6-5fd0-46f2-8b73-5d9d36db65e9.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_fwpomfret.jpg",
      "bar_code": null,
      "weight_description": "350",
      "gross_weight_description": "490",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Freshwater Pomfret - Yeri Vavval",
      "entity_id": 220,
      "spicy": null,
      "gramsperunit": "650",
      "weight_from": "500",
      "weight_to": "700",
      "url_key": "freshwater-pomfret-yeri-vawaal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_FWPOMFRET",
      "type_id": "simple",
      "plu_code": 302,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "220_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_freshwater-pomfret-yeri-vawaal-fish",
      "tag_label": null,
      "sort_order": 15,
      "category_id": 58,
      "category_name": "Elite Offers",
      "upsell_products": []
    },
    {
      "price": "479.0000",
      "special_price": null,
      "short_description": "Degutted, slice cut & packed with head & tail",
      "sku": "SF_BPOMFRET",
      "thumb": "https://assets.tendercuts.in/product/S/F/dc2c5ff1-596c-4aec-bbce-290fa283b721.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_bpomfret.jpg",
      "bar_code": null,
      "weight_description": "280",
      "gross_weight_description": "420",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Black Pomfret",
      "entity_id": 221,
      "spicy": null,
      "gramsperunit": "630",
      "weight_from": "400",
      "weight_to": "600",
      "url_key": "black-pomfret-vawaal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_BPOMFRET",
      "type_id": "simple",
      "plu_code": 310,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "221_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_black-pomfret-vawaal-fish",
      "tag_label": null,
      "sort_order": 12,
      "category_id": 58,
      "category_name": "Elite Offers",
      "upsell_products": []
    },
    {
      "price": "215.0000",
      "special_price": null,
      "short_description": "Fish gutted & packed without head",
      "sku": "SF_IM",
      "thumb": "https://assets.tendercuts.in/product/S/F/ace681e8-36d3-4d75-aa3d-cac0bdcb515d.jpg",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_im.jpg",
      "bar_code": null,
      "weight_description": "330",
      "gross_weight_description": "420",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Indian Mackerel",
      "entity_id": 216,
      "spicy": null,
      "gramsperunit": "630",
      "weight_from": "480",
      "weight_to": "600",
      "url_key": "indian-makerel-ayilai-kana-keluthi-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_IM",
      "type_id": "simple",
      "plu_code": 303,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "216_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_indian-makerel-ayilai-kana-keluthi-fish",
      "tag_label": null,
      "sort_order": 13,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "225.0000",
      "special_price": null,
      "short_description": "Degutted, Bengali cut & packed with head & tail",
      "sku": "SF_CATLA",
      "thumb": "https://assets.tendercuts.in/product/S/F/da08b3c1-d92a-49bb-8664-7db731ddc3d5.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_catla.jpg",
      "bar_code": null,
      "weight_description": "560",
      "gross_weight_description": "840",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Catla Bengali Cut - With Head",
      "entity_id": 217,
      "spicy": null,
      "gramsperunit": "1100",
      "weight_from": "800",
      "weight_to": "1100",
      "url_key": "catla-bengal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_CATLA",
      "type_id": "simple",
      "plu_code": 311,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "217_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_catla-bengal-fish",
      "tag_label": null,
      "sort_order": 9,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "209.0000",
      "special_price": null,
      "short_description": "Degutted, Bengali cut & packed with head & tail",
      "sku": "SF_ROHU",
      "thumb": "https://assets.tendercuts.in/product/S/F/81c06c41-5527-4be3-bf21-0e9dff6f26c3.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_rohu.jpg",
      "bar_code": null,
      "weight_description": "560",
      "gross_weight_description": "840",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Rohu Bengali Cut - With Head",
      "entity_id": 218,
      "spicy": null,
      "gramsperunit": "1100",
      "weight_from": "800",
      "weight_to": "1100",
      "url_key": "rohu-bengal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_ROHU",
      "type_id": "simple",
      "plu_code": 307,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "218_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_rohu-bengal-fish",
      "tag_label": "Trending",
      "sort_order": 4,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "429.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_TREVLLY",
      "thumb": "https://assets.tendercuts.in/product/S/F/0974ac18-c34a-4f0d-a3ec-2a1d1296f525.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_trevlly.jpg",
      "bar_code": null,
      "weight_description": "300",
      "gross_weight_description": "420",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Trevally",
      "entity_id": 219,
      "spicy": null,
      "gramsperunit": "750",
      "weight_from": "500",
      "weight_to": "700",
      "url_key": "trevlly-parai-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_TREVLLY",
      "type_id": "simple",
      "plu_code": 313,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "219_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_trevlly-parai-fish",
      "tag_label": null,
      "sort_order": 17,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "165.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_FWPOMFRET",
      "thumb": "https://assets.tendercuts.in/product/S/F/cab653d6-5fd0-46f2-8b73-5d9d36db65e9.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_fwpomfret.jpg",
      "bar_code": null,
      "weight_description": "350",
      "gross_weight_description": "490",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Freshwater Pomfret - Yeri Vavval",
      "entity_id": 220,
      "spicy": null,
      "gramsperunit": "650",
      "weight_from": "500",
      "weight_to": "700",
      "url_key": "freshwater-pomfret-yeri-vawaal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_FWPOMFRET",
      "type_id": "simple",
      "plu_code": 302,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "220_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_freshwater-pomfret-yeri-vawaal-fish",
      "tag_label": null,
      "sort_order": 8,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "479.0000",
      "special_price": null,
      "short_description": "Degutted, slice cut & packed with head & tail",
      "sku": "SF_BPOMFRET",
      "thumb": "https://assets.tendercuts.in/product/S/F/dc2c5ff1-596c-4aec-bbce-290fa283b721.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_bpomfret.jpg",
      "bar_code": null,
      "weight_description": "280",
      "gross_weight_description": "420",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Black Pomfret",
      "entity_id": 221,
      "spicy": null,
      "gramsperunit": "630",
      "weight_from": "400",
      "weight_to": "600",
      "url_key": "black-pomfret-vawaal-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_BPOMFRET",
      "type_id": "simple",
      "plu_code": 310,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "221_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_black-pomfret-vawaal-fish",
      "tag_label": null,
      "sort_order": 27,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "769.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_SEABASS",
      "thumb": "https://assets.tendercuts.in/product/S/F/75fcc3f5-8f77-4cb5-97e2-b82ff73ff9f3.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_seabass.jpg",
      "bar_code": null,
      "weight_description": "560",
      "gross_weight_description": "840",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Sea Bass",
      "entity_id": 222,
      "spicy": null,
      "gramsperunit": "1100",
      "weight_from": "800",
      "weight_to": "1200",
      "url_key": "sea-bass-koduva-fish",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SEABASS",
      "type_id": "simple",
      "plu_code": 309,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "222_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_sea-bass-koduva-fish",
      "tag_label": null,
      "sort_order": 22,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "239.0000",
      "special_price": null,
      "short_description": "35-45 Pieces Deshelled",
      "sku": "SF_PRAWN",
      "thumb": "https://assets.tendercuts.in/product/S/F/3649da52-b25a-42c8-8ffe-ab39cc781046.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_prawn.jpg",
      "bar_code": null,
      "weight_description": "240",
      "gross_weight_description": "270",
      "visibility": 3,
      "status": 1,
      "uom": 72,
      "name": "Prawns Medium - Deshelled",
      "entity_id": 226,
      "spicy": null,
      "gramsperunit": "500",
      "weight_from": "480",
      "weight_to": "500",
      "url_key": "prawn-eral-seafood",
      "is_scannable": 2,
      "pieces": "35 to 45",
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_PRAWN",
      "type_id": "simple",
      "plu_code": 300,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "226_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_prawn-eral-seafood",
      "tag_label": "Trending",
      "sort_order": 1,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "359.0000",
      "special_price": null,
      "short_description": "20-30 Pieces",
      "sku": "SF_PRAWN_BIG",
      "thumb": "https://assets.tendercuts.in/product/t/i/tiger_prawns.jpg",
      "external_img": "https://assets.tendercuts.in/product/t/i/tiger_prawns.jpg",
      "bar_code": null,
      "weight_description": "240",
      "gross_weight_description": "270",
      "visibility": 3,
      "status": 1,
      "uom": 72,
      "name": "Prawns Large - Deshelled & Deveined",
      "entity_id": 227,
      "spicy": null,
      "gramsperunit": "500",
      "weight_from": "480",
      "weight_to": "500",
      "url_key": "prawn-eral-seafood-big",
      "is_scannable": 1,
      "pieces": "20 to 30",
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_PRAWN_BIG",
      "type_id": "simple",
      "plu_code": 385,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "227_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": null,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_prawn-eral-seafood-big",
      "tag_label": null,
      "sort_order": 21,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "379.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_SHELLA",
      "thumb": "https://assets.tendercuts.in/product/S/F/864ea58b-8ded-4849-bd3b-eb96d6eaf415.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_shella.jpg",
      "bar_code": null,
      "weight_description": "240",
      "gross_weight_description": "360",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Barracuda /Sheela",
      "entity_id": 233,
      "spicy": null,
      "gramsperunit": "620",
      "weight_from": "400",
      "weight_to": "600",
      "url_key": "sheela-fish-barracuda",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SHELLA",
      "type_id": "simple",
      "plu_code": 312,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "233_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_sheela-fish-barracuda",
      "tag_label": null,
      "sort_order": 16,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "275.0000",
      "special_price": null,
      "short_description": "Fish gutted & packed without head",
      "sku": "SF_LADY_FISH",
      "thumb": "https://assets.tendercuts.in/product/S/F/b0bfb740-008b-46c5-83c3-34488ee5486b.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_lady_fish.jpg",
      "bar_code": null,
      "weight_description": "310",
      "gross_weight_description": "360",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Lady Fish",
      "entity_id": 234,
      "spicy": null,
      "gramsperunit": "580",
      "weight_from": "480",
      "weight_to": "550",
      "url_key": "lady-fish-kilangan",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_LADY_FISH",
      "type_id": "simple",
      "plu_code": 305,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "234_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_lady-fish-kilangan",
      "tag_label": null,
      "sort_order": 10,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "275.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_PEARL_SPOT",
      "thumb": "https://assets.tendercuts.in/product/S/F/4fd4c183-31ce-4d00-8050-279843eed716.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_pearl_spot.jpg",
      "bar_code": null,
      "weight_description": "330",
      "gross_weight_description": "420",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Karimeen",
      "entity_id": 244,
      "spicy": null,
      "gramsperunit": "630",
      "weight_from": "480",
      "weight_to": "600",
      "url_key": "karimeen-pearl-spot",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_PEARL_SPOT_CURRY_MEEN",
      "type_id": "simple",
      "plu_code": 304,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "244_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_karimeen-pearl-spot",
      "tag_label": null,
      "sort_order": 20,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "209.0000",
      "special_price": null,
      "short_description": "Fish gutted & packed without head -- 35-40 pcs.",
      "sku": "SF_ANCHOVY",
      "thumb": "https://assets.tendercuts.in/product/S/F/3808faee-4ab2-4035-9b7c-849cec906707.jpg",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_anchovy.jpg",
      "bar_code": null,
      "weight_description": "280",
      "gross_weight_description": "330",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Anchovy (Medium)",
      "entity_id": 245,
      "spicy": null,
      "gramsperunit": "550",
      "weight_from": "480",
      "weight_to": "550",
      "url_key": "nethili-anchovy",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_ANCHOVY",
      "type_id": "simple",
      "plu_code": 398,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "245_Chennai",
      "hsn_code": "0",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_nethili-anchovy",
      "tag_label": null,
      "sort_order": 11,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "349.0000",
      "special_price": null,
      "short_description": "Processed & packed with leg",
      "sku": "SF_BLUE_CRAB",
      "thumb": "https://assets.tendercuts.in/product/S/F/92f7c23a-9844-47c1-b294-ad73d80c8693.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_blue_crab.jpg",
      "bar_code": null,
      "weight_description": "290",
      "gross_weight_description": "360",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Crab / Nandu",
      "entity_id": 246,
      "spicy": null,
      "gramsperunit": "630",
      "weight_from": "480",
      "weight_to": "600",
      "url_key": "kadal-nandu-blue-crab",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_BLUE_CRAB",
      "type_id": "simple",
      "plu_code": 301,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "246_Chennai",
      "hsn_code": "3063300",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_kadal-nandu-blue-crab",
      "tag_label": null,
      "sort_order": 25,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "155.0000",
      "special_price": null,
      "short_description": "Customise your cut",
      "sku": "RM_SF_SEER",
      "thumb": "https://assets.tendercuts.in/product/R/M/ea3aaeff-d7d5-4825-8be4-cbfc921b9545.webp",
      "external_img": "https://assets.tendercuts.in/product/s/e/seer_vanjram.jpg",
      "bar_code": null,
      "weight_description": "100",
      "gross_weight_description": "100",
      "visibility": 2,
      "status": 1,
      "uom": 72,
      "name": "Seer Fish / Vanjaram",
      "entity_id": 249,
      "spicy": null,
      "gramsperunit": "1000",
      "weight_from": "100",
      "weight_to": "100",
      "url_key": "seer-fish",
      "is_scannable": 0,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": null,
      "type_id": "simple",
      "plu_code": null,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "249_Chennai",
      "hsn_code": null,
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": null,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_seer-fish",
      "tag_label": null,
      "sort_order": 110,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": [1416, 1417, 1213, 1217, 316, 876, 877]
    },
    {
      "price": "209.0000",
      "special_price": null,
      "short_description": "Customize your cut",
      "sku": "RM_SF_PRAWN",
      "thumb": "https://assets.tendercuts.in/product/R/M/d8d8e3b9-82cb-444f-a024-9cd20891a45d.webp",
      "external_img": "https://assets.tendercuts.in/productNone",
      "bar_code": null,
      "weight_description": "100",
      "gross_weight_description": "100",
      "visibility": 2,
      "status": 1,
      "uom": 72,
      "name": "Prawn / Eral",
      "entity_id": 252,
      "spicy": null,
      "gramsperunit": "1000",
      "weight_from": "100",
      "weight_to": "100",
      "url_key": "prawns",
      "is_scannable": 1,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": null,
      "type_id": "simple",
      "plu_code": null,
      "weight_label": null,
      "qty_inc": "1",
      "feed_id": "252_Chennai",
      "hsn_code": null,
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": null,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_prawns",
      "tag_label": null,
      "sort_order": 100,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": [623, 660, 1212, 226, 227, 866]
    },
    {
      "price": "599.0000",
      "special_price": null,
      "short_description": "4 to 6 Pieces",
      "sku": "SF_SEER",
      "thumb": "https://assets.tendercuts.in/product/S/F/40e84831-1f82-42de-b3f6-d5f50dd57278.webp",
      "external_img": "https://assets.tendercuts.in/product/s/e/seer_full_slice.jpg",
      "bar_code": null,
      "weight_description": "480",
      "gross_weight_description": "500",
      "visibility": 3,
      "status": 1,
      "uom": 72,
      "name": "Full Slice - Seer Fish / Vanjaram",
      "entity_id": 316,
      "spicy": null,
      "gramsperunit": "750",
      "weight_from": "600",
      "weight_to": "650",
      "url_key": "vanjaram-seer-fish-slices",
      "is_scannable": 2,
      "pieces": "4 - 6",
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SEER",
      "type_id": "simple",
      "plu_code": 314,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "316_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_vanjaram-seer-fish-slices",
      "tag_label": null,
      "sort_order": 6,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "819.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_INDIAN_SALMON",
      "thumb": "https://assets.tendercuts.in/product/S/F/558079a0-8e58-4dfb-b230-0922fe061fc8.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_indian_salmon.jpg",
      "bar_code": null,
      "weight_description": "560",
      "gross_weight_description": "840",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Indian Salmon/Kaala",
      "entity_id": 322,
      "spicy": null,
      "gramsperunit": "1100",
      "weight_from": "800",
      "weight_to": "1200",
      "url_key": "indian-salmon",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_INDIAN_SALMON",
      "type_id": "simple",
      "plu_code": 350,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "322_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_indian-salmon",
      "tag_label": null,
      "sort_order": 23,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "235.0000",
      "special_price": null,
      "short_description": "Three Spot Crab - Kan Nandu",
      "sku": "SF_THREE_SPOT_CRAB_KAN_NANDU",
      "thumb": "https://assets.tendercuts.in/product/S/F/b443352e-be68-451b-ae81-7d8cc5828f2e.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_three_spot_crab_kan_nandu.jpg",
      "bar_code": null,
      "weight_description": "300",
      "gross_weight_description": "380",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Three Spot Crab / Kan Nandu",
      "entity_id": 341,
      "spicy": null,
      "gramsperunit": "550",
      "weight_from": "480",
      "weight_to": "600",
      "url_key": "three-spot-crab-kan-nandu",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_THREE_SPOT_CRAB",
      "type_id": "simple",
      "plu_code": 318,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "341_Chennai",
      "hsn_code": "3063300",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_three-spot-crab-kan-nandu",
      "tag_label": null,
      "sort_order": 18,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "299.0000",
      "special_price": null,
      "short_description": "Degutted, curry cut & packed without head",
      "sku": "SF_TUNA",
      "thumb": "https://assets.tendercuts.in/product/S/F/a24538c1-17ec-42c6-a9e7-206108990267.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_tuna.jpg",
      "bar_code": null,
      "weight_description": "540",
      "gross_weight_description": "780",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Tuna",
      "entity_id": 342,
      "spicy": null,
      "gramsperunit": "1200",
      "weight_from": "900",
      "weight_to": "1300",
      "url_key": "soorai-tuna",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_TUNA",
      "type_id": "simple",
      "plu_code": 319,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "342_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_soorai-tuna",
      "tag_label": null,
      "sort_order": 26,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "229.0000",
      "special_price": null,
      "short_description": "Processed & packed with Rings",
      "sku": "SF_SQUID_KANAVAI",
      "thumb": "https://assets.tendercuts.in/product/S/F/15689b87-5df9-49d3-98b3-82a874df1930.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_squid_kanavai.jpg",
      "bar_code": null,
      "weight_description": "240",
      "gross_weight_description": "270",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Squid",
      "entity_id": 347,
      "spicy": null,
      "gramsperunit": "550",
      "weight_from": "480",
      "weight_to": "550",
      "url_key": "squid-kanavai",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SQUID",
      "type_id": "simple",
      "plu_code": 324,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "347_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": null,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_squid-kanavai",
      "tag_label": null,
      "sort_order": 29,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "499.0000",
      "special_price": null,
      "short_description": "Degutted whole fish",
      "sku": "SF_WHITE_POMFRET",
      "thumb": "https://assets.tendercuts.in/product/S/F/0137cf3f-1d29-46b5-aa2e-bd43bc72998e.jpg",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_white_pomfret.jpg",
      "bar_code": null,
      "weight_description": "330",
      "gross_weight_description": "380",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "White Pomfret",
      "entity_id": 348,
      "spicy": null,
      "gramsperunit": "550",
      "weight_from": "480",
      "weight_to": "550",
      "url_key": "chinese-pomfert-chinese-vavval",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_WHITE_POMFRET",
      "type_id": "simple",
      "plu_code": 325,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "348_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_chinese-pomfert-chinese-vavval",
      "tag_label": null,
      "sort_order": 30,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "299.0000",
      "special_price": null,
      "short_description": "5 - 6 Slices",
      "sku": "SF_KADAL_VIRAL",
      "thumb": "https://assets.tendercuts.in/product/S/F/817c14f3-97ad-4f5d-a489-8191af73dec7.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_kadal_viral.jpg",
      "bar_code": null,
      "weight_description": "490",
      "gross_weight_description": "510",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Sea Butterfish / Kadal Viral",
      "entity_id": 349,
      "spicy": null,
      "gramsperunit": "800",
      "weight_from": "490",
      "weight_to": "510",
      "url_key": "sea-butterfish-kadal-viral",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_KADAL_VIRAL",
      "type_id": "simple",
      "plu_code": 326,
      "weight_label": "Gms",
      "qty_inc": "1.35",
      "feed_id": "349_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": null,
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_sea-butterfish-kadal-viral",
      "tag_label": null,
      "sort_order": 34,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "159.0000",
      "special_price": null,
      "short_description": "Fish gutted & packed without head",
      "sku": "SF_MATHI",
      "thumb": "https://assets.tendercuts.in/product/S/F/942f54c9-b0cb-4002-b3dd-6bdf8f4bd5f7.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_mathi.jpg",
      "bar_code": null,
      "weight_description": "240",
      "gross_weight_description": "260",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Sardine - Mathi",
      "entity_id": 354,
      "spicy": null,
      "gramsperunit": "520",
      "weight_from": "480",
      "weight_to": "520",
      "url_key": "indian-oil-sardine-mathi",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SARDINE",
      "type_id": "simple",
      "plu_code": 331,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "354_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_indian-oil-sardine-mathi",
      "tag_label": null,
      "sort_order": 5,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "329.0000",
      "special_price": null,
      "short_description": "Degutted, steak cut & packed with head & tail",
      "sku": "SF_EMPEROR",
      "thumb": "https://assets.tendercuts.in/product/S/F/b186532a-8bd5-41f3-81a5-0886a3d1a1dd.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_emperor.jpg",
      "bar_code": null,
      "weight_description": "490",
      "gross_weight_description": "350",
      "visibility": 4,
      "status": 1,
      "uom": 72,
      "name": "Emperor / Vilai Meen",
      "entity_id": 361,
      "spicy": null,
      "gramsperunit": "600",
      "weight_from": "500",
      "weight_to": "700",
      "url_key": "emperor-sliced-vilai-meen",
      "is_scannable": 2,
      "pieces": "3 pcs",
      "serves": "3 - 5",
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_EMPEROR",
      "type_id": "simple",
      "plu_code": 317,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "361_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_emperor-sliced-vilai-meen",
      "tag_label": null,
      "sort_order": 14,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    },
    {
      "price": "289.0000",
      "special_price": null,
      "short_description": "Pieces",
      "sku": "SF_SHARK",
      "thumb": "https://assets.tendercuts.in/product/S/F/3c68ca5e-e838-45e3-ab1f-a0d0fd079581.webp",
      "external_img": "https://assets.tendercuts.in/product/s/f/sf_shark.jpg",
      "bar_code": null,
      "weight_description": "480",
      "gross_weight_description": "510",
      "visibility": 3,
      "status": 1,
      "uom": 72,
      "name": "Shark Slices",
      "entity_id": 377,
      "spicy": null,
      "gramsperunit": "850",
      "weight_from": "480",
      "weight_to": "510",
      "url_key": "shark-sliced-sura-meen",
      "is_scannable": 2,
      "pieces": null,
      "serves": null,
      "uom_value": "Gms",
      "tax_class_id": 0,
      "parent_sku": "RM_SF_SHARK",
      "type_id": "simple",
      "plu_code": 333,
      "weight_label": "Gms",
      "qty_inc": "1",
      "feed_id": "377_Chennai",
      "hsn_code": "3049900",
      "video_url": null,
      "per_month_subs_price": 0,
      "video_label": null,
      "external_vendor_markup": "1.0000",
      "tag": [],
      "show_gross_net": true,
      "deeplink": "https://tcuts.in/WSuf/product?c_redirection_link=product_shark-sliced-sura-meen",
      "tag_label": null,
      "sort_order": 19,
      "category_id": 14,
      "category_name": "Sea Food",
      "upsell_products": []
    }
];
